[package]
name = "imageflow_core"
version = "0.1.0"
authors = ["Nathanael Jones <nathanael.jones@gmail.com>"]
build = "conan_cargo_build.rs"
links = "imageflow_c"
workspace = "../"

[lib]
name = "imageflow_core"
doctest = false

[dependencies]
libc = "0.2.0"
clap = "2"
time = "*"
rustc-serialize = "*"
threadpool = "1.0"
serde = "*"
serde_json = "*"
serde_derive = "*"
lazy_static = "0.1.*"
json = "*"
imageflow_types = { path = "../imageflow_types", version = "*" }
petgraph = "^0.2.8"
daggy = "^0.4.1"
clippy = "0.0.97"
imageflow_helpers = { path = "../imageflow_helpers", version = "*" }

[dev-dependencies]
hyper = "*"


[build-dependencies]
cmake = "0.1.17"

[profile.release]
debug = true