[package]
name = "imageflow_core"
version = "0.1.0"
authors = ["Nathanael Jones <nathanael.jones@gmail.com>"]
build = "conan_cargo_build.rs"
links = "imageflow_c"
workspace = "../"

[lib]
name = "imageflow_core"
doctest = false

[dependencies]
libc = "0.2"

# time
time = "*"
chrono =  "0.4"

# serialization
serde = "*"
serde_json = "*"
serde_derive = "*"
rustc-serialize = "*"

#lazy static
lazy_static = "0.2"

# fast hashes, crypto hashs
twox-hash = "1"
fnv = "*"
blake2-rfc = "*"

## Crate-specific dependencies

clap = "2"
threadpool = "1"
petgraph = "0.4"
daggy = "0.5"

gif = "*"
gif-dispose="*"

url = "*"
uuid = { version = "0.5", features = ["v4"] }

imageflow_types = { path = "../imageflow_types", version = "*" }
imageflow_helpers = { path = "../imageflow_helpers", version = "*" }
imageflow_riapi = { path = "../imageflow_riapi", version = "*" }


[dev-dependencies]
hyper = { version = "*" }


[build-dependencies]
cmake = "0.1.17"


#cp ../../../cargo/target/x86_64-unknown-linux-gnu/release/cargo /home/n/.cargo/bin/