sudo: required
language: generic
services:
- docker
cache:
  ccache: true
  cargo: true
  directories:
  - "$HOME/.conan/data"
matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    env: PACKAGE_SUFFIX=x86_64-linux-gcc48 DOCKER_IMAGE=imazen/build_if_gcc48 UPLOAD_BUILD=True 
    sudo: required
    services:
    - docker
  - os: linux
    dist: trusty
    env: PACKAGE_SUFFIX=x86_64-linux-gcc54 DOCKER_IMAGE=imazen/build_if_gcc54 UPLOAD_BUILD=True
    sudo: required
    services:
    - docker
  - os: osx
    osx_image: xcode7.3
    env: PACKAGE_SUFFIX=x86_64-apple-darwin-xcode73 UPLOAD_BUILD=True  TARGET=x86_64-apple-darwin 
    language: rust
    rust: nightly-2016-11-03
  - os: linux
    dist: trusty
    env: PACKAGE_SUFFIX=x86_64-linux-gcc49 DOCKER_IMAGE=imazen/build_if_gcc49 UPLOAD_BUILD=True 
    sudo: required
    services:
    - docker
  - os: linux
    dist: trusty
    env: UPLOAD_BUILD=False COVERAGE=True VALGRIND=True PACKAGE_SUFFIX=x86_64-linux-gcc54 DOCKER_IMAGE=imazen/build_if_gcc54
    sudo: required
    services:
    - docker
install:
- ci/travis_install.sh
script:
- ci/travis_run.sh
deploy:
  provider: s3
  access_key_id: AKIAIMZ7QOL24GUASH6A
  secret_access_key:
    secure: izS5sgSOhDwjuQaFTTgMlhUd5759ZnuoxxoFDo41XZATNw58P6FtzdfslfoVa+xXjq/1N0GDAM+ENm7XYNITVqq1aJARYKy5X+IUwVKQw/UYx0rb1X2ZV7oDHsFvY5pSRiVFD1tQ0fZ9JKAkb1LTnSutfVYHNYvPHiyYQf07nig=
  bucket: imageflow-nightlies
  acl: public_read
  skip_cleanup: true
  local_dir: artifacts/upload
  on:
    repo: imazen/imageflow
