sudo: required
language: generic

services:
  - docker

cache:
  ccache: true
  cargo: true
  directories:
    - $HOME/.conan/data

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      env: DOCKER_IMAGE=imazen/build_if_gcc54 RUST_CHANNEL=stable UPLOAD_BUILD=true COVERALLS=True JOB_NAME="build_if_gcc54_rust_stable"
      sudo: required
      services:
        - docker
    - os: linux
      dist: trusty
      env: DOCKER_IMAGE=imazen/build_if_gcc54 RUST_CHANNEL=nightly UPLOAD_BUILD=true VALGRIND=true JOB_NAME="build_if_gcc54_rust_nightly"
      sudo: required
      services:
        - docker
    - os: osx
      osx_image: xcode7.3
      env: TARGET=x86_64-apple-darwin RUST_CHANNEL=stable UPLOAD_BUILD=true JOB_NAME="xcode73"
      language: rust
      rust: stable
#    - os: osx
#      osx_image: xcode8
#      rust: stable
#      env: TARGET=x86_64-apple-darwin RUST_CHANNEL=stable UPLOAD_BUILD=true JOB_NAME="xcode8"
#      language: rust
    - os: linux
      dist: trusty
      env: DOCKER_IMAGE=imazen/build_if_gcc48 RUST_CHANNEL=stable UPLOAD_BUILD=true JOB_NAME="build_if_gcc48_rust_stable"
      sudo: required
      services:
        - docker
    - os: linux
      dist: trusty
      env: DOCKER_IMAGE=imazen/build_if_gcc49 RUST_CHANNEL=stable UPLOAD_BUILD=true JOB_NAME="build_if_gcc49_rust_stable"
      sudo: required
      services:
        - docker
install:
  - ci/travis_install.sh

script:
  - ci/travis_run.sh
