sudo: required
langage: generic

services:
  - docker

cache:
  - ccache
  - cargo
  directories:
    - $HOME/.conan/data

matrix:
  fast_finish: true
  include:
    - os: linux
      env: DOCKER_IMAGE=imazen/build_if_gcc54 RUST_CHANNEL=stable UPLOAD_BUILD=true COVERALLS=True JOB_NAME="build_if_gcc54_rust_stable"
    - os: linux
      env: DOCKER_IMAGE=imazen/build_if_gcc54 RUST_CHANNEL=nightly UPLOAD_BUILD=true VALGRIND=true JOB_NAME="build_if_gcc54_rust_nightly"
    - os: osx
      osx_image: xcode7.3
      rust: stable
      env: TARGET=x86_64-apple-darwin
      env: RUST_CHANNEL=stable UPLOAD_BUILD=true JOB_NAME="xcode73"
    - os: linux
      env: DOCKER_IMAGE=imazen/build_if_gcc_48 RUST_CHANNEL=stable UPLOAD_BUILD=true JOB_NAME="build_if_gcc48_rust_stable"
    - os: linux
      env: DOCKER_IMAGE=imazen/build_if_gcc_49 RUST_CHANNEL=stable UPLOAD_BUILD=true JOB_NAME="build_if_gcc49_rust_stable"
install:
  - .travis/install.sh

script:
  - .travis/run.sh
