os:
  - linux

language:
  - cpp

sudo:
  - required

services:
  - docker
  
env:
  matrix:
    - GCC_VERSION=48 
    - GCC_VERSION=49
    - GCC_VERSION=52
    - GCC_VERSION=53

matrix:
   include:
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env:
       - os: osx
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env:
       - os: osx
         osx_image: xcode6.4 # apple-clang 6.1
         language: generic
         env:
       - os: osx
         osx_image: xcode6.2 # apple-clang 6.0
         language: generic
         env:

install:
  - .travis/install.sh

before_script:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --zerocounters


script:
  - .travis/run.sh

after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info # capture coverage info
- lcov --remove coverage.info 'tests/*' '.conan/*' '/usr/*' --output-file coverage.info # filter out system and test code
- lcov --list coverage.info # debug before upload
- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls
