os:
  - linux

language:
  - cpp

sudo:
  - required

services:
  - docker

env:
  matrix:
    - GCC_VERSION=48
    - GCC_VERSION=49
    - GCC_VERSION=52
    - GCC_VERSION=53
    - GCC_VERSION=48 COVERALLS=True
    - GCC_VERSION=48 VALGRIND=True


matrix:
   include:
       - os: osx
         osx_image: xcode8
         language: generic
         env:
       - os: osx
         osx_image: xcode7.3 
         language: generic
         env:
       - os: osx
         osx_image: xcode7.1 
         language: generic
         env:

install:
  - .travis/install.sh

script:
  - .travis/run.sh
