os:
  - linux

language:
  - cpp

sudo:
  - required

env:
  global:
   - secure: "ZCnVl71wkTwMMS4F0aiYQJ6DHW3sPRPAto2daS0KjZ7fF0Z7mgWuF2yr2MARuUWRLYyVMp4rC493ZnB4NBLf1vzFmX1ZzPzAt1JTkHr6PHpaPEDlWs26XvkwirW/EPMk6vjpO0MSfzPLoo9z3Ph1csbAF6lxRgFtCo9QsCRfCA0="

addons:
  coverity_scan:
    project:
      name: "memsharded/imageflow"
      description: "Imageflow + imageflow server"
    notification_email: james@conan.io
    build_command_prepend: "chmod +x .travis/pre_coverity.sh && .travis/pre_coverity.sh"
    build_command:   "conan build"
    branch_pattern: coverity_scan

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
  - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cd ..
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo apt-get install libstdc++-4.8-dev

script:
  - echo "Nothing to do in coverity_scan"
