sudo: required
language: generic
services:
- docker
cache:
  ccache: true
  directories:
  - "$HOME/.conan/data"
  - "$HOME/.cargo"
  - "$TRAVIS_BUILD_DIR/target/release"
  - "$TRAVIS_BUILD_DIR/target/debug"
matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    env: TARGET_CPU=x86_64 PACKAGE_SUFFIX=x86_64-linux-gcc48-eglibc219 DOCKER_IMAGE=imazen/build_if_gcc48 UPLOAD_BUILD=True FETCH_COMMIT_SUFFIX=linux64
    sudo: required
    services:
    - docker
  - os: linux
    dist: trusty
    env: TARGET_CPU=sandybridge PACKAGE_SUFFIX=x86_64-sandybridge-linux-gcc54-glibc223 DOCKER_IMAGE=imazen/build_if_gcc54 UPLOAD_BUILD=True UPLOAD_DOCS=True FETCH_COMMIT_SUFFIX=linux64_sandybridge_glibc223
    sudo: required
    services:
    - docker
  - os: linux
    dist: trusty
    env: TARGET_CPU=haswell PACKAGE_SUFFIX=x86_64-haswell-linux-gcc54-glibc223 DOCKER_IMAGE=imazen/build_if_gcc54 UPLOAD_BUILD=True UPLOAD_DOCS=True FETCH_COMMIT_SUFFIX=linux64_haswell_glibc223
    sudo: required
    services:
    - docker
  - os: osx
    osx_image: xcode7.3
    #Should be compatible with El Capitan forward. xcode7.3.1
    env: TARGET_CPU=sandybridge PACKAGE_SUFFIX=x86_64-sandybridge-mac-osx10_11 UPLOAD_BUILD=True TARGET=x86_64-apple-darwin FETCH_COMMIT_SUFFIX=mac64
    language: rust
    rust: nightly-2016-11-03
  - os: linux
    dist: trusty
    env: UPLOAD_BUILD=False COVERAGE=True VALGRIND=True TARGET_CPU=sandybridge P PACKAGE_SUFFIX=x86_64-sandy_valgrind_linux-gcc54 DOCKER_IMAGE=imazen/build_if_gcc54
    sudo: required
    services:
    - docker
install:
- ci/travis_install.sh
script:
- ci/travis_run.sh
before_deploy:
  - export GITHUB_FILES="$(ls artifacts/upload/releases/v*/imageflow-v*.tar.gz)"
  - echo "Planning to upload ${GITHUB_FILES} to GitHub"
deploy:
  - provider: s3
    access_key_id: AKIAIMZ7QOL24GUASH6A
    secret_access_key:
      secure: izS5sgSOhDwjuQaFTTgMlhUd5759ZnuoxxoFDo41XZATNw58P6FtzdfslfoVa+xXjq/1N0GDAM+ENm7XYNITVqq1aJARYKy5X+IUwVKQw/UYx0rb1X2ZV7oDHsFvY5pSRiVFD1tQ0fZ9JKAkb1LTnSutfVYHNYvPHiyYQf07nig=
    bucket: imageflow-nightlies
    acl: public_read
    skip_cleanup: true
    local_dir: artifacts/upload
    on:
      branch: master
      condition: $UPLOAD_BUILD = True
  - provider: s3
    access_key_id: AKIAIMZ7QOL24GUASH6A
    secret_access_key:
      secure: izS5sgSOhDwjuQaFTTgMlhUd5759ZnuoxxoFDo41XZATNw58P6FtzdfslfoVa+xXjq/1N0GDAM+ENm7XYNITVqq1aJARYKy5X+IUwVKQw/UYx0rb1X2ZV7oDHsFvY5pSRiVFD1tQ0fZ9JKAkb1LTnSutfVYHNYvPHiyYQf07nig=
    bucket: imageflow-nightlies
    acl: public_read
    skip_cleanup: true
    local_dir: artifacts/upload
    on:
      tags: true
      condition: $UPLOAD_BUILD = True
  - deploy:
    provider: releases
    api_key:
      - secure: "U9jYsyiN3u9GVPbMtroFDyDmUIrzV6vyvtfCAY7I9YiepjrL+zP7FzmZU8sk56ukV1ZRM7QXP1fs1hTeAkcEPgfhITvqnCsQRcGzIEg3Ri5OZ+HVjt7ATGqVCndadL/cBhydmpq7cDfEIxhdzhmvfhcg/fjqX4oVOh6EM+dUG3E="
    file_glob: true
    file: "${GITHUB_FILES}"
    skip_cleanup: true
    prerelease: true
    on:
      tags: true
      condition: $UPLOAD_BUILD = True

after_success:
  - if [[ "$FETCH_COMMIT_SUFFIX" == "linux64_glibc223" ]]; then ./ci/travis_trigger_docker_cloud.sh; fi