build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
    RUST_BACKTRACE: 1
    OPENSSL_INCLUDE_DIR: C:\OpenSSL\include
    OPENSSL_LIB_DIR: C:\OpenSSL\lib
    OPENSSL_LIBS: ssleay32:libeay32:gdi32:User32
configuration: Release

platform:
- x64
- x86

matrix:
  fast_finish: true


#We install nasm in case libjpeg-turbo has to be built from source
install:
  - SET "GIT_COMMIT=%APPVEYOR_REPO_COMMIT%"
  - SET "CI_SEQUENTIAL_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%"
  - SET "CI_BUILD_URL=https://ci.appveyor.com/project/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%/build/%APPVEYOR_BUILD_VERSION%"
  - SET "CI_JOB_TITLE=AppVeyor %APPVEYOR_BUILD_VERSION% %APPVEYOR_JOB_NAME%"
  - SET "CI_JOB_URL=https://ci.appveyor.com/project/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%/branch/%APPVEYOR_REPO_BRANCH%/job/%APPVEYOR_JOB_ID%"
  - SET "CI_STRING=name:AppVeyor job_id:%APPVEYOR_JOB_ID% build_id:%APPVEYOR_BUILD_ID% build_number:%APPVEYOR_BUILD_NUMBER% build_version:%APPVEYOR_BUILD_VERSION% account_name:%APPVEYOR_ACCOUNT_NAME% project_slug:%APPVEYOR_PROJECT_SLUG% tag_name:%APPVEYOR_REPO_TAG_NAME% pull_request_number:%APPVEYOR_PULL_REQUEST_NUMBER% branch:%APPVEYOR_REPO_BRANCH%"
  - SET "CI_TAG=%APPVEYOR_REPO_TAG_NAME%"
  - SET "CI_RELATED_BRANCH=%APPVEYOR_REPO_BRANCH%"
  - SET "CI_PULL_REQUEST_INFO=%APPVEYOR_PULL_REQUEST_NUMBER%"
  - SET "GIT_OPTIONAL_BRANCH="
  - if "%CI_PULL_REQUEST_INFO%"=="" SET "GIT_OPTIONAL_BRANCH=%CI_RELATED_BRANCH%"
  - SET "ARTIFACT_SERIES_NAME=pullrequest"
  - if "%CI_PULL_REQUEST_INFO%"=="" SET "ARTIFACT_SERIES_NAME=%CI_TAG%"
  - if "%ARTIFACT_SERIES_NAME%"=="" SET "ARTIFACT_SERIES_NAME=%CI_RELATED_BRANCH%"
  - git rev-parse --short HEAD>tempfile.txt&set /p SHORT_COMMIT=<tempfile.txt
  - git describe --always --tags --long>tempfile.txt&set /p DESCRIBE_ALWAYS_LONG=<tempfile.txt
  - if "%CI_TAG%"=="" SET "ARTIFACT_NAME=imageflow-nightly-%ARTIFACT_SERIES_NAME%-%CI_SEQUENTIAL_BUILD_NUMBER%-%DESCRIBE_ALWAYS_LONG%-%PLATFORM%"
  - if NOT "%CI_TAG%"=="" SET "ARTIFACT_NAME="imageflow-%CI_TAG%-%SHORT_COMMIT%-%PLATFORM%"
  - SET "ESTIMATED_ARTIFACT_URL=https://ci.appveyor.com/api/buildjobs/%APPVEYOR_JOB_ID%/artifacts/%ARTIFACT_NAME%.zip"
  - echo. && echo. && echo Estimated upload URL && echo. && echo %ESTIMATED_ARTIFACT_URL% && echo. && echo.
  - echo "GIT_COMMIT=%GIT_COMMIT%" && echo "CI_STRING=%CI_STRING%" && echo "CI_TAG=%CI_TAG%" && echo "CI_RELATED_BRANCH=%CI_RELATED_BRANCH%" && echo "CI_PULL_REQUEST_INFO=%CI_PULL_REQUEST_INFO%" && echo "ARTIFACT_SERIES_NAME=%ARTIFACT_SERIES_NAME%"
  - echo. && echo. echo Installing
  - if "%PLATFORM%"=="x86" SET RUST_TARGET=i686-pc-windows-msvc
  - if "%PLATFORM%"=="x64" SET RUST_TARGET=x86_64-pc-windows-msvc
  - if "%PLATFORM%"=="x86" SET BITS=32
  - if "%PLATFORM%"=="x64" SET BITS=64
  - curl -L -o openssl.exe "https://s3-us-west-2.amazonaws.com/imageflow-resources/tools/Win%BITS%OpenSSL-1_0_2j.exe"
  - openssl.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"
  - SET RUST_ARTIFACT=2016-11-03/rust-nightly-%RUST_TARGET%.exe
  - curl -L -o nasminst.exe http://libgd.blob.core.windows.net/nasm/nasm-2.07-installer.exe
  - start /wait nasminst.exe /S
  - echo Fetching https://static.rust-lang.org/dist/%RUST_ARTIFACT%
  - curl -L -o  install_rust.exe https://static.rust-lang.org/dist/%RUST_ARTIFACT%
  - install_rust.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - set PATH=%PATH%;%PYTHON%/Scripts/;C:\Program Files (x86)\nasm;C:\Program Files (x86)\Rust\bin
  - pip.exe install conan
  - conan user # It creates the conan data directory

test_script:
  - echo %PATH%
  - conan --version
  - cmake --version
  - rustc -V
  - cargo -V
  - nasm -v
  - cd c_components
  - mkdir build
  - cd build
  - if "%PLATFORM%"=="x86" set CONAN_ARCH=x86
  - if "%PLATFORM%"=="x64" set CONAN_ARCH=x86_64
  - SET PATH=%PATH%;C:\MinGW\bin
  - conan install --scope build_tests=True -o shared=True --build missing -s build_type=Release -s arch=%CONAN_ARCH%  -u ../
  - conan build ../
  - cd ..
  - conan export imazen/testing
  - cd ..
  - cd imageflow_core
  - conan install --build missing -s build_type=Release -s arch=%CONAN_ARCH%
  - cargo test --target=%RUST_TARGET% 
  - cargo doc --no-deps
  - cd ..
  - cd imageflow_server
  - cargo test --target=%RUST_TARGET% 
  - cargo doc --no-deps 
  - cd ..
  - cd imageflow_tool
  - cargo test --target=%RUST_TARGET% 
  - cargo doc --no-deps
  - cargo build --target=%RUST_TARGET% --bin imageflow_tool
  - echo. && echo Displaying embedded info (debug build imageflow_tool)
  - ..\target\%RUST_TARGET%\debug\imageflow_tool.exe diagnose --show-compilation-info
  - ..\target\%RUST_TARGET%\debug\imageflow_tool.exe diagnose --self-test
  - cd ..
  - cd imageflow_abi
  - cargo test --target=%RUST_TARGET% 
  - cargo doc --no-deps
  - cd ..
  - cd imageflow_types
  - cargo test --target=%RUST_TARGET% 
  - cargo doc --no-deps
  - cd ..
  - echo. && echo. && echo. && echo Building optimized binaries && echo. && echo. && echo.
  - cd imageflow_tool
  - cargo build --target=%RUST_TARGET% --release
  - echo. && echo Displaying embedded info (release build of imageflow_tool) && echo .
  - ..\target\%RUST_TARGET%\release\imageflow_tool.exe diagnose --show-compilation-info
  - ..\target\%RUST_TARGET%\release\imageflow_tool.exe diagnose --self-test
  - cd ..
  - cd imageflow_server
  - cargo build --target=%RUST_TARGET% --release
  - cd ..
  - cd imageflow_abi
  - cargo build --target=%RUST_TARGET% --release
  - cd ..
  - mkdir artifacts
  - mkdir artifacts\staging
  - mkdir artifacts\staging\doc
  - mkdir artifacts\staging\headers
  - dir target\%RUST_TARGET%\release\
  - xcopy /Y target\%RUST_TARGET%\release\flow-proto1.exe  artifacts\staging\
  - xcopy /Y target\%RUST_TARGET%\release\imageflow_server.exe  artifacts\staging\
  - xcopy /Y target\%RUST_TARGET%\release\imageflow.dll  artifacts\staging\
  - xcopy /Y target\%RUST_TARGET%\release\imageflow_tool.exe  artifacts\staging\
  - xcopy /Y bindings\headers\*.h  artifacts\staging\headers
  - xcopy /Y /E target\doc  artifacts\staging\doc
  - cd artifacts\staging
  - 7z a -r "..\..\%ARTIFACT_NAME%.zip" *
  - cd ..\..
  - appveyor PushArtifact "%ARTIFACT_NAME%.zip"


artifacts:
  - path: 'artifacts/*'
    name: Rust binaries

