build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
configuration: Release

platform:
- x64
- x86

#We install nasm in case libjpeg-turbo has to be built from source
install:
  - if "%PLATFORM%"=="x86" SET RUST_TARGET=i686-pc-windows-msvc
  - if "%PLATFORM%"=="x64" SET RUST_TARGET=x86_64-pc-windows-msvc
  - SET RUST_ARTIFACT=rust-1.11.0-%RUST_TARGET%.exe
  - curl -L -o nasminst.exe http://libgd.blob.core.windows.net/nasm/nasm-2.07-installer.exe
  - start /wait nasminst.exe /S
  - echo Fetching https://static.rust-lang.org/dist/%RUST_ARTIFACT%
  - curl -L -o  install_rust.exe https://static.rust-lang.org/dist/%RUST_ARTIFACT%
  - install_rust.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - set PATH=%PATH%;%PYTHON%/Scripts/;C:\Program Files (x86)\nasm;C:\Program Files (x86)\Rust\bin
  - pip.exe install conan
  - conan user # It creates the conan data directory

test_script:
  - echo %PATH%
  - rustc -V
  - cargo -V
  - mkdir build
  - cd build
  - if "%PLATFORM%"=="x86" conan install --scope build_tests=True -o shared=True --build missing -s build_type=Release -s arch=x86 -u ../
  - if "%PLATFORM%"=="x64" conan install --scope build_tests=True -o shared=True --build missing -s build_type=Release -s arch=x86_64  -u ../
  - conan build ../
  - cd ..
  - conan export lasote/testing
  - cd imageflow_core
  - conan install --build missing
  - cargo test
  - cargo build --target=%RUST_TARGET% --release
  - cd ..
  - cd imageflow_tool
  - cargo build --target=%RUST_TARGET% --release
  - mkdir ..\artifacts
  - mkdir ..\artifacts\staging
  - xcopy target\release\flow-proto1  ..\artifacts\staging\
  - cd ..
  - set ARTIFACT_NAME="%APPVEYOR_PROJECT_SLUG%_%APPVEYOR_BUILD_NUMBER%-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_REPO_COMMIT%-%APPVEYOR_REPO_TAG_NAME%_%PLATFORM%.zip"
  - 7z a "%ARTIFACT_NAME%.zip" artifacts/staging/*
  - appveyor PushArtifact "%ARTIFACT_NAME%.zip"


artifacts:
  - path: 'artifacts/*'
    name: Rust binaries

