build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

configuration: Release

platform:
- x86
- x64

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user # It creates the conan data directory

test_script:
  - mkdir build
  - cd build
  - if "%PLATFORM%"=="x86" conan install --file ../conanfile.py -o build_tests=True --build missing  -s build_type=Release -s arch=x86
  - if "%PLATFORM%"=="x64" conan install --file ../conanfile.py -o build_tests=True --build missing  -s build_type=Release -s arch=x86_64
  - cmake ../ -DENABLE_TEST=ON && cmake --build . && ctest -V -C Release

