build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
    OPENSSL_INCLUDE_DIR: C:\OpenSSL\include
    OPENSSL_LIB_DIR: C:\OpenSSL\lib
    OPENSSL_LIBS: ssleay32:libeay32

configuration: Release

platform:
- x64
- x86

#We install nasm in case libjpeg-turbo has to be built from source
install:
  - if "%PLATFORM%"=="x86" SET BITS=32
  - if "%PLATFORM%"=="x64" SET BITS=64
  - if "%PLATFORM%"=="x86" SET RUST_TARGET=i686-pc-windows-msvc
  - if "%PLATFORM%"=="x64" SET RUST_TARGET=x86_64-pc-windows-msvc
  - SET RUST_ARTIFACT=rust-1.11.0-%RUST_TARGET%.exe
  - ps: Start-FileDownload "http://slproweb.com/download/Win${env:BITS}OpenSSL-1_0_2h.exe"
  - Win%BITS%OpenSSL-1_0_2h.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"
  - curl -L -o nasminst.exe http://libgd.blob.core.windows.net/nasm/nasm-2.07-installer.exe
  - start /wait nasminst.exe /S
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/($env:RUST_ARTIFACT)' }
  - "%RUST_ARTIFACT% /VERYSILENT /NORESTART /DIR=C:\Program Files\ (x86)\Rust"
  - set PATH=%PATH%;%PYTHON%/Scripts/;C:\Program Files (x86)\nasm;C:\Program Files (x86)\Rust\bin
  - pip.exe install conan
  - conan user # It creates the conan data directory
  - rustc -V
  - cargo -V

test_script:
  - mkdir build
  - cd build
  - if "%PLATFORM%"=="x86" conan install --scope build_tests=True -o shared=True --build missing -s build_type=Release -s arch=x86 -u ../
  - if "%PLATFORM%"=="x64" conan install --scope build_tests=True -o shared=True --build missing -s build_type=Release -s arch=x86_64  -u ../
  - conan build ../
  - cd ..
  - conan export lasote/testing
  - cd wrappers/server
  - conan install --build missing
  - ps: (Get-Content conan_cargo_build.rs).replace('\', '\\') | Set-Content conan_cargo_build.rs
  - cargo build --target=%RUST_TARGET% --release
  - 7z a "%APPVEYOR_PROJECT_SLUG%_%APPVEYOR_REPO_TAG_NAME%_%PLATFORM%.zip" *
  - appveyor PushArtifact "%APPVEYOR_PROJECT_SLUG%_%APPVEYOR_REPO_TAG_NAME%_%PLATFORM%.zip"



artifacts:
  - path: 'wrappers/server/target/**/flow-proto1.exe'
    name: Rust binaries

