[workspace]
members = ["imageflow_helpers", "imageflow_types", "imageflow_riapi", "imageflow_core", "imageflow_abi", "imageflow_tool", "imageflow_server"]


[profile.release]
debug = true

[dependencies.regex]
features=["pattern"]

[dependencies.openssl]
features=["v102"]


[dependencies.openssl-sys]
features=["ossl102"]
