[package]
name = "imageflow_tool_lib"
version = "0.1.0"
authors = ["Nathanael Jones <nathanael.jones@gmail.com>"]
workspace = "../"

[dependencies]
imageflow_core = { path = "../imageflow_core", version = "*" }
imageflow_types = { path = "../imageflow_types", version = "*" }
libc = "0.2.0"
clap = "2"
time = "*"
rustc-serialize = "*"
threadpool = "1"
serde = "*"
serde_json = "*"
imageflow_helpers = { path = "../imageflow_helpers", version = "*" }

[[bin]]
name = "imageflow_tool"
path = "src/main.rs"
doc = false
