[package]
name = "imageflow_serde"
version = "0.1.0"
authors = ["Nathanael Jones <imageflow@imazen.io>"]
workspace = "../"

[lib]
name="imageflow_serde"

[dependencies]
serde = "0.8"
serde_json = "0.8"
serde_macros = "0.8"