lb:
  image: dockercloud/haproxy
  autorestart: always
  links:
    - web
  ports:
    - "80:3000"
  roles:
    - global
web:
  image: imazen/imageflow_server
  autorestart: always
  links:
    - redis
  environment:
    - NAME=Friendly Users
  deployment_strategy: high_availability
  target_num_containers: 1 #4
  working_dir: /home/conan/imageflow
  entrypoint: /home/conan/imageflow/imageflow_server
  user: conan
redis:
  image: redis
  autorestart: always
  environment:
    - REDIS_PASS=password
#    - REDIS_APPENDONLY=yes
#    - REDIS_APPENDFSYNC=always
