imageflow:
  autoredeploy: true
  entrypoint: '/bin/sh -c "sudo chown -R imageflow /home/imageflow/ && /home/imageflow/imageflow_server start --demo --bind-address 0.0.0.0 --port 3000 --data-dir /home/imageflow/data/"'
  environment:
    - RUST_BACKTRACE=1
  image: 'imazen/imageflow_server_unsecured:latest'
  ports:
    - '80:3000'
  restart: always
  roles:
    - global
  volumes:
    - '/mnt/imageflow/server_data:/home/imageflow/data'
