[package]
name = "imageflow_helpers"
version = "0.1.0"
authors = ["Nathanael Jones <nathanael.jones@gmail.com>"]
workspace = "../"

[dependencies]
libc = "0.2"

# time
time = "*"
chrono =  "0.4"

# serialization
serde = "*"
serde_json = "*"
serde_derive = "*"
rustc-serialize = "*"

#lazy static
lazy_static = "0.1.*"

# fast hashes, crypto hashs
twox-hash = "1.0"
fnv = "*"
blake2-rfc = "*"

# regex
regex = "*"


zip = { version = "0.2", default-features = false }


# HTTPS is a little bit of a nightmare

hyper = "*"
reqwest = "*"
hyper-native-tls = "*"

backtrace = "0.3"


[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.dependencies]
openssl = "*"
hyper-openssl = "*"
