[package]
name = "imageflow_helpers"
version = "0.1.0"
authors = ["Nathanael Jones <nathanael.jones@gmail.com>"]
workspace = "../"

[dependencies]
regex = "*"
hyper = "*"
blake2-rfc = "*"
lazy_static = "*"
bit-vec = "*"
twox-hash = "1.0.0"
fnv = "*"

[profile.release]
debug = true