[package]
name = "imageflow_types"
version = "0.1.0"
authors = ["Nathanael Jones <imageflow@imazen.io>"]
workspace = "../"
build = "build.rs"

[lib]
name="imageflow_types"
doctest = false

[dependencies]
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
lazy_static = "*"

[build-dependencies]
quick-error = "1.1.0"
chrono =  "0.2"