[package]
name = "imageflow_types"
version = "0.1.0"
authors = ["Nathanael Jones <imageflow@imazen.io>"]
workspace = "../"
build = "build.rs"

[lib]
name="imageflow_types"
doctest = false

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
lazy_static = "*"
regex = "*"
imageflow_helpers = { path = "../imageflow_helpers", version = "*" }
chrono ="*"

[build-dependencies]
quick-error = "1.1.0"
chrono =  "0.2"
