[package]
name = "imageflow_server"
version = "0.1.0"
authors = ["Nathanael Jones <nathanael.jones@gmail.com>"]
workspace = "../"

[replace]
"openssl:0.8.2" = { path = "../../../github/rust-openssl/openssl" }
"openssl-sys:0.7.17"= { path = "../../../github/rust-openssl/openssl-sys" }
#"openssl:0.8.2" = { git = "https://github.com/imazen/rust-openssl.git", branch="master"}
#"openssl-sys:0.7.17"= { git = "https://github.com/imazen/rust-openssl.git", branch="master"}


[dependencies]
libc = "0.2.0"
clap = "2"
router = "*"
iron = "*"
time = "*"
hyper = "*"
rustc-serialize = "*"
threadpool = "1.0"
serde = "*"
serde_json = "*"
imageflow_core = { path = "../imageflow_core", version = "*" }

[build-dependencies]
cmake = "0.1.17"
